CREATE TABLE indexes (symbol VARCHAR(100) NOT NULL PRIMARY KEY );

INSERT INTO indexes(symbol) VALUES('TST1');


CREATE TABLE index_values (
	symbol VARCHAR(100) NOT NULL ,
	value_date TIMESTAMP NOT NULL ,
	value DECIMAL NOT NULL 
	);
ALTER TABLE index_values  ADD  
    PRIMARY KEY (symbol,value_date);

INSERT INTO index_values(symbol, value_date, value) VALUES('TST1','2008-08-08 20:08:08','13.2');
INSERT INTO index_values(symbol, value_date, value) VALUES('TST1','2004-08-08 20:08:08','10');

CREATE TABLE users(
	id bigint generated by default as identity (start with 1),
	login VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	is_admin BIT NOT NULL);
ALTER TABLE users ADD
	UNIQUE (login);
ALTER TABLE users ADD
	PRIMARY KEY (id);
	
INSERT INTO users (id,login,password,is_admin) VALUES (1,'test1','test',0);
INSERT INTO users (id,login,password,is_admin) VALUES (2,'test2','test',1);


CREATE TABLE available_indexes (user_id INTEGER NOT NULL, index_symbol VARCHAR(100) NOT NULL);
ALTER TABLE available_indexes ADD
	PRIMARY KEY (user_id, index_symbol);
ALTER TABLE available_indexes ADD
	FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE available_indexes ADD
	FOREIGN KEY (index_symbol) REFERENCES indexes(symbol);
INSERT INTO available_indexes (user_id,index_symbol) VALUES (1,'TST1');